networks:
  docknet:
    external: true

services:
  nextjs:
    logging:
      options:
        max-size: 5m
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        MYUSERNAME: ${MYUSERNAME}
        MYUSERGROUP: ${MYUSERGROUP}
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/home/${MYUSERNAME}/webapp
      - ../appservices/uploads:/home/${MYUSERNAME}/appservices/uploads
      - ../appservices/uploads/logs/npm:/root/.npm/_logs
      - /home/${MYUSERNAME}/webapp/.next
      - /home/${MYUSERNAME}/webapp/node_modules
    tty: true
    networks:
      - docknet
    labels:
      - traefik.enable=true
      - traefik.http.services.nextjs.loadbalancer.server.port=3000
      - traefik.http.routers.nextjs.rule=Host(`postroyka.localhost`)
      - traefik.http.routers.nextjs.entrypoints=web