networks:
  docknet:
    external: true

services:
  nextjs:
    logging:
      options:
        max-size: 5m
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/home/appuser/webapp
      - ../appservices/uploads:/home/appuser/appservices/uploads
      - ../appservices/uploads/logs/npm:/root/.npm/_logs
      - /home/appuser/webapp/.next
      - /home/appuser/webapp/node_modules
    tty: true
    networks:
      - docknet
    labels:
      - traefik.enable=true
      - traefik.http.services.nextjs.loadbalancer.server.port=3000
      - traefik.http.routers.postroyka.rule=Host(`postroyka.localhost`)
      - traefik.http.routers.postroyka.entrypoints=web